promotedai/promoted-ruby-client

README.md, lib/promoted/ruby/client.rb, lib/promoted/ruby/client/options.rb
- fix: issue with to_underscore being called on symbol fields …
- fix: remove platform_id
- fix: remove event_api_timestamp
- fix: LogRequest.request is an array
- refactor: change spacing in comments
- docs: add some README documentation
TESTING=manual
=> fix: multiple - fix LogRequest, add docs, clean

README.md, lib/promoted/ruby/client/options.rb
=> feat: support paging offsets

lib/promoted/ruby/client/options.rb
=> fix: paging logic where request.paging is not set

.gitignore, lib/promoted/ruby/client/options.rb, spec/promoted/ruby/client_spec.rb
TESTING=manual.  changed specs.
=> fix: remove limit.  rename 'offset' to 'from'

README.md, dev.md
=> docs: readme - push instructions and pushed version

README.md, lib/promoted/ruby/client/options.rb
'from' is a reserved keyword in python so it's easier to just change this now.
TESTING=spec
=> fix: rename Paging.from to .offset

lib/promoted/ruby/client.rb, lib/promoted/ruby/client/constants.rb, lib/promoted/ruby/client/request_builder.rb, lib/promoted/ruby/client/util.rb, spec/promoted/ruby/client_spec.rb, spec/shared/testdata.rb
Basic experiment handling\rTESTING=unit
Enums will be strings from the API\rTESTING=unit
More delivery logic\rTESTING=unit
=> feat: More work on deliver\rTESTING=unit

lib/promoted/ruby/client.rb, lib/promoted/ruby/client/errors.rb, lib/promoted/ruby/client/faraday_http_client.rb
A pluggable logger that defaults to the built-in one, plus some error logging in obvious places.
=> Error handling POC\rTESTING=unit

Gemfile.lock, README.md, dev.md, lib/promoted/ruby/client/version.rb
=> Bump version for 0.1.3

Gemfile.lock, dev.md, lib/promoted/ruby/client/version.rb
=> bump version to 0.1.7

Gemfile.lock, dev.md, lib/promoted/ruby/client/version.rb
=> bump version to 0.1.9

Gemfile.lock, dev.md, lib/promoted/ruby/client/version.rb
=> feat: bump version to 0.1.16

Gemfile.lock, dev.md, lib/promoted/ruby/client/version.rb
This includes a breaking change.  We're not bumping since we only have 1 customer currently using the client.
TESTING=unit tests
=> feat: bump version to 0.1.18

Gemfile.lock, dev.md, lib/promoted/ruby/client/version.rb
=> feat: bump version to 0.1.21

lib/promoted/ruby/client.rb
Also contains smaller changes:
- Makes sure we don't send shadow traffic on error.
- Checks that the response is a Hash.
TESTING=Ran unit tests
=> fix: move response interpretation into catch block

Gemfile.lock, README.md, dev.md, lib/promoted/ruby/client/request_builder.rb, lib/promoted/ruby/client/validator.rb, lib/promoted/ruby/client/version.rb, spec/promoted/ruby/client/log_request_builder_spec.rb, spec/promoted/ruby/client/validator_spec.rb, spec/promoted/ruby/client_spec.rb, spec/promoted/ruby/functional_test.rb, spec/shared/testdata.rb
PRO-5544
BREAKING CHANGE: renames existing field
TESTING=none
=> feat: rename log_user_id to anon_user_id

dev.md
=> docs: update deploy instructions

lib/promoted/ruby/client/pager.rb, spec/promoted/ruby/client/pager_spec.rb
PRO-5680
This was existing code that I should have updated.
I also did some extra refactoring.
TESTING=ran spec
=> fix: invalid validation of large offset case

Gemfile.lock, dev.md, lib/promoted/ruby/client.rb, lib/promoted/ruby/client/validator.rb, lib/promoted/ruby/client/version.rb, spec/promoted/ruby/client/validator_spec.rb, spec/promoted/ruby/client_spec.rb
=> feat: bump version to 5.0.0

spec/promoted/ruby/client/validator_spec.rb
=> feat: add more validator specs

README.md, lib/promoted/ruby/client/validator.rb
=> feat: UserInfo.ignore_usage
